export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">

            <header><p style={{ backgroundColor: "blue", padding: "1rem" }}>Headerasdf</p></header>
            <body>{children}</body>

        </html>
    )
}
