export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <header><p style={{ backgroundColor: "lightblue", padding: "1rem" }}>Header</p></header>
            <body>{children}</body>
            <footer><p style={{ backgroundColor: "lightblue", padding: "1rem" }}>Footer</p></footer>
        </html>
    )
}
