import { Metadata } from "next"
import "./styles.css"
import { ThemeProvider } from "@/components/theme-provider"



export const metadata: Metadata = {
    title: {
        absolute: "",
        default: "Next.js Learning",
        template: "%s | Codevolution"
    },
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    type="text/css"

                    href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
                />
                <link
                    rel="stylesheet"
                    type="text/css"
                    href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
                />
            </head>
            <ThemeProvider>
                <body>
                    <header><p style={{ backgroundColor: "lightblue", padding: "1rem" }}>Header</p></header>
                    {children}
                    <footer><p style={{ backgroundColor: "lightblue", padding: "1rem" }}>Footer</p></footer>
                </body>
            </ThemeProvider>
        </html>
    )
}
