import React from 'react'

export const metadata = {
    title: 'Profile',
    description: 'Generated by Next.js',
}


function About() {
    return (
        <div>About</div>
    )
}

export default About